### ISSUE TITLE
Cannot Revoke Ephemeral Certificates

### ISSUE THREAD

**Issue by carteralbrecht** [Keyfactor/ejbca-vault-pki-engine#13]
We are using EJBCA in [Ephemeral CA mode](https://doc.primekey.com/ejbca/ejbca-installation/maximizing-performance#MaximizingPerformance-EphemeralCertificates)

We have enabled [Accept Revocations for Non-Existing Entries](https://doc.primekey.com/ejbca/ejbca-operations/ejbca-ca-concept-guide/certificate-authority-overview/ca-fields#CAFields-AcceptRevocationsforNon-ExistingEntriesAccept_Revocations_of_Non-Existing_Entry) on the CA in order to be able to revoke ephemeral certificates.

However, when using this plugin, any attempts to revoke Ephemeral Certificates are met with

```
Error writing data to <EJBCA_MOUNT>/revoke: Error making API request.

URL: PUT https://<OUR_VAULT_ADDRESS>/v1/<EJBCA_MOUNT>/revoke
Code: 403. Errors:

* 1 error occurred:
	* permission denied
```

I have also tried 
- using `/revoke-with-key` and supplying the private key too
- using the `serial_number` param instead of the `certificate` param

**Comment by carteralbrecht** [comment]
Correct me if I am wrong, but this looks relevant. Seems that the certificate bundle is being fetched from storage by serial even if the `certificate` param was used. If this is the case, it is probably failing because ephemeral certs aren't stored. 

https://github.com/Keyfactor/ejbca-vault-pki-engine/blob/314c0f495613407f6730d8851e582b128d4d5cde/path_revoke.go#L94-L105

https://github.com/Keyfactor/ejbca-vault-pki-engine/blob/314c0f495613407f6730d8851e582b128d4d5cde/certs_util.go#L53-L54

**Comment by carteralbrecht** [comment]
After further research, the `403` was given because `/revoke` requires ["create", "update"], and I only had ["create"].

However, after fixing this, I receive
```
Error writing data to .../revoke: Error making API request.
URL: PUT .../revoke
Code: 500. Errors:
* 1 error occurred:
  * returned certificate bytes were empty 
```
 This is almost surely a result of the code snippets linked in my previous comment.

Is it possible to support revocation of ephemeral certificates?

**Comment by m8rmclaren** [comment]
Hey @carteralbrecht,
Happy to hear that the `403` issue is resolved.

Based on the context, one of the following must be true if the EJBCA Vault PKI Engine doesn't have the certificate entry in its backend:
* The role used to issue the certificate has `no_store=true` - the Engine didn't store the issued certificates in its storage backend.
* The certificate was not issued by the EJBCA Vault PKI Engine.
* The EJBCA Vault PKI Engine was restarted and the storage backend was erased.

The EJBCA Vault PKI Engine attempts to replicate the in-tree Vault PKI Engine's API, which doesn't enable revocation of certificates that are not stored in its backend. Since the EJBCA Vault PKI Engine is a proxy to EJBCA and is not a CA itself, I think that it makes sense to enable this use-case.

You're a few steps ahead of me, but we can accomplish this by bypassing the fetch to the Engine's backend storage if the user passed the certificate (`/revoke`) or the certificate and private key (`/revoke-with-key`).

We need to decide how the revoked certificate entry is created, or if it should be created at all, for these scenarios. I'll make sure that this decision is documented in the changelog.

I've created a working branch for this fix found [here](https://github.com/Keyfactor/ejbca-vault-pki-engine/tree/revoke-56831).

**Comment by carteralbrecht** [comment]
Thanks for the update, yes the certificate was not persisted because we had turned off [Use_Certificate_Storage](https://doc.primekey.com/ejbca/ejbca-operations/ejbca-ca-concept-guide/certificate-authority-overview/ca-fields#CAFields-UseCertificateStorageUse_Certificate_Storage) in our EJBCA SaaS in order to enable ephemeral certificates.

We did not change the vault role setting. 

I think that bypassing the fetch when the certificate is provided by the caller makes sense.

I don't know exactly how the internals work regarding a revoked certificate entry, but I will mention that I would expect to still be able to call the embedded OCSP endpoint in the certificate to check revocation (not sure if that requires a revoked certificate entry in this context)

**Comment by jtgarner-keyfactor** [comment]
@carteralbrecht  You will get an OCSP response for any certificate added to the CRL, regardless of cert storage in vault. If the revocation call is successful, providing validation responses is on EJBCA at that point.

**Comment by carteralbrecht** [comment]
Awesome! so sounds like this is all possible then once the change is made to bypass the fetch

**Comment by m8rmclaren** [comment]
Hey @carteralbrecht,
If your security policy allows for it, you're welcome to test drive the changes in [this branch](https://github.com/Keyfactor/ejbca-vault-pki-engine/tree/revoke-56831) and I can make any adjustments necessary.

**Comment by carteralbrecht** [comment]
@m8rmclaren  Thanks for the quick turnaround. I'm going to see if we can get this installed and verify

**Comment by carteralbrecht** [comment]
Verified that the plugin works for revoking ephemeral certs, this can be closed.
