### ISSUE TITLE
Add Auto renewal of the certificate to the Vault Plugin

### ISSUE THREAD

**Issue by svenska-primekey** [Keyfactor/ejbca-vault-pki-engine#21]
**Is your feature request related to a problem or specific use case? Please describe.**

Vault has the capability with the Vault PKI engine for a Vault Sub CA to renew a certificate with a private key that Vault agents access to use the updated cert/key.

**Describe the solution you'd like**

Add this capability to the EJBCA Vault PKI engine to do the same thing.

**Describe alternatives you've considered**

Go to competitor and not use Keyfactor!

**Product deployment**
Please complete the following information:
 - Deployment format: Vault Container, EJBCA software deployment
 - Version EJBCA version 7.10.x - working on upgrading in the next quarter

**Additional context**
- https://developer.hashicorp.com/vault/docs/secrets/pki/considerations#automate-leaf-certificate-renewal
- https://developer.hashicorp.com/vault/docs/agent-and-proxy/agent/template#certificates

**Comment by m8rmclaren** [comment]
Hi @svenska-primekey

This feature is already available when using the [Vault Agent Template feature](https://developer.hashicorp.com/vault/docs/agent-and-proxy/agent/template#renewals-and-updating-secrets). There are two main patterns, and both of them support renewal. 

1. The first is with the `secret` template function:

    ```yaml
    >> cert.pem.tmpl
    {{ with secret "ejbca/issue/example-dot-com" "common_name=foo.example.com" }}
    # Leaf Certificate 
    {{ .Data.certificate }}
    
    # Private Key
    {{ .Data.private_key }}
    {{ end }}
    {{ with secret "ejbca/cert/ca_chain" }}
    # Issuer
    {{ .Data.certificate }}
    # Intermediates + Root
    {{ .Data.ca_chain }}
    {{ end }}
    ```

2. The second is with the `pkiCert` template function:

    ```yaml
    >> cert.pem.tmpl
    {{ with pkiCert "ejbca/issue/example-dot-com" "common_name=foo.example.com" }}
    # Leaf Certificate 
    {{ .Data.Cert }}
    
    # Private Key
    {{ .Data.Key }}
    {{ end }}
    {{ with secret "ejbca/cert/ca_chain" }}
    # Issuer
    {{ .Data.certificate }}
    # Intermediates + Root
    {{ .Data.ca_chain }}
    {{ end }}
    ```

You'll notice that the only difference between the HashiCorp docs and the examples in this comment are that `pki` is replaced with `ejbca`. This is because the EJBCA Vault PKI Engine (mounted at `ejbca` in this case) implements a subset of the in-tree PKI engine's API.

For completeness, the EJBCA Vault PKI Engine also fully supports the [Non-Renewable Leased Secrets](https://developer.hashicorp.com/vault/docs/agent-and-proxy/agent/template#non-renewable-leased-secrets) flow when `generate_lease=true` in the Vault role. In the examples, the Vault role was called `example-dot-com`.
